apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  type: ClusterIP
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-ws
      port: 9001
      targetPort: 9001
